name: Autograding I/O Tests

on: [push]

jobs:
  io-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run case 1
        run: |
          python main.py < tests/io/case1.in | diff -q --strip-trailing-cr - tests/io/case1.out


      - name: Run case 2
        run: |
          python main.py < tests/io/case2.in | diff -q --strip-trailing-cr - tests/io/case2.out




